In [2]:
import tensorflow as tf 
import matplotlib.pyplot as plt 
import numpy as np 

image = tf.image.decode_jpeg(tf.read_file("220px-Batian_Nelion_and_pt_Slade_in_the_foreground_Mt_Kenya.JPG"), channels=3) 
grey_image = tf.image.rgb_to_grayscale(image) 
##print(grey_image_2.shape) 
##Image.fromarray(np.asarray(image)).show() 
##plt.imshow(grey_image) 
##plt.show() 
sess = tf.InteractiveSession() 
# plt.imshow(grey_image) 
##plt.show() 
# print(sess.run(grey_image))

[[[153]
  [153]
  [154]
  ...
  [244]
  [248]
  [249]]

 [[152]
  [153]
  [154]
  ...
  [232]
  [235]
  [238]]

 [[151]
  [152]
  [153]
  ...
  [220]
  [221]
  [222]]

 ...

 [[129]
  [172]
  [223]
  ...
  [108]
  [104]
  [109]]

 [[210]
  [158]
  [183]
  ...
  [105]
  [ 79]
  [107]]

 [[205]
  [133]
  [186]
  ...
  [ 89]
  [ 15]
  [ 93]]]


/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
